const Books = [
  {
    id: "1",
    title: "A Hora da Estrela",
    productPrice: "25.00",
    productImg: require("../../assets/books/a_hora_da_estrela.jpg"),
    description: "Livro escrito por Clarice Lispector.",
  },
  {
    id: "2",
    title: "A Moreninha",
    productPrice: "20.00",
    productImg: require("../../assets/books/a_moreninha.jpg"),
    description: "Um romance de Joaquim Manuel de Macedo.",
  },
  {
    id: "3",
    title: "Capitães da Areia",
    productPrice: "30.00",
    productImg: require("../../assets/books/capitaes_da_areia.jpg"),
    description: "Romance de Jorge Amado sobre meninos de rua.",
  },
  {
    id: "4",
    title: "Dom Casmurro",
    productPrice: "22.50",
    productImg: require("../../assets/books/dom_casmurro.jpg"),
    description: "Livro famoso de Machado de Assis.",
  },
  {
    id: "5",
    title: "Iracema",
    productPrice: "27.50",
    productImg: require("../../assets/books/iracema.jpg"),
    description: "Romance escrito por José de Alencar.",
  },
  {
    id: "6",
    title: "Macunaíma",
    productPrice: "35.00",
    productImg: require("../../assets/books/macunaima.jpg"),
    description: "Obra de Mário de Andrade, uma importante obra modernista.",
  },
  {
    id: "7",
    title: "Mayombe",
    productPrice: "32.00",
    productImg: require("../../assets/books/mayombe.jpg"),
    description: "Livro de Pepetela sobre a luta pela independência de Angola.",
  },
  {
    id: "8",
    title: "Memórias de um Sargento de Milícias",
    productPrice: "18.00",
    productImg: require("../../assets/books/memorias_de_um_sargento_de_milicias.jpg"),
    description: "Romance de Manuel Antônio de Almeida.",
  },
  {
    id: "9",
    title: "Memórias Póstumas de Brás Cubas",
    productPrice: "24.00",
    productImg: require("../../assets/books/memorias_postumas.jpg"),
    description: "Outra obra famosa de Machado de Assis.",
  },
  {
    id: "10",
    title: "Memórias Sentimentais de João Miramar",
    productPrice: "29.00",
    productImg: require("../../assets/books/memorias_sentimentais_de_joao_miramar.jpg"),
    description: "Livro escrito por Oswald de Andrade.",
  },
  {
    id: "11",
    title: "O Alienista",
    productPrice: "21.00",
    productImg: require("../../assets/books/o_alienista.jpg"),
    description: "Uma das histórias mais conhecidas de Machado de Assis.",
  },
  {
    id: "12",
    title: "O Auto da Compadecida",
    productPrice: "26.00",
    productImg: require("../../assets/books/o_auto_da_compadecida.jpg"),
    description: "Peça teatral escrita por Ariano Suassuna.",
  },
  {
    id: "13",
    title: "O Cortiço",
    productPrice: "28.00",
    productImg: require("../../assets/books/o_cortico.jpg"),
    description: "Romance naturalista de Aluísio Azevedo.",
  },
  {
    id: "14",
    title: "O Guarani",
    productPrice: "23.50",
    productImg: require("../../assets/books/o_guarani.jpg"),
    description: "Romance indianista de José de Alencar.",
  },
  {
    id: "15",
    title: "O Seminarista",
    productPrice: "19.50",
    productImg: require("../../assets/books/o_seminarista.jpg"),
    description: "Livro de Bernardo Guimarães.",
  },
  {
    id: "16",
    title: "Quincas Borba",
    productPrice: "31.00",
    productImg: require("../../assets/books/quincas_borba.jpg"),
    description: "Romance de Machado de Assis.",
  },
  {
    id: "17",
    title: "Terra Sonâmbula",
    productPrice: "33.00",
    productImg: require("../../assets/books/terra_sonambula.jpg"),
    description: "Livro de Mia Couto sobre a guerra civil em Moçambique.",
  },
  {
    id: "18",
    title: "Vidas Secas",
    productPrice: "34.00",
    productImg: require("../../assets/books/vidas_secas.jpg"),
    description: "Romance de Graciliano Ramos sobre a vida no sertão nordestino.",
  }
];

export default Books;
