const products = [
  {
    id: "1",
    title: "Uniforme Escolar - Camiseta",
    productPrice: "20.00",
    productImg: require("../../assets/products/uniforme.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "2",
    title: "Conjunto de Lápis de Cor",
    productPrice: "10.50",
    productImg: require("../../assets/products/cor.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "3",
    title: "Mochila Escolar",
    productPrice: "25.99",
    productImg: require("../../assets/products/mochila.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "4",
    title: "Estojo Escolar",
    productPrice: "5.00",
    productImg: require("../../assets/products/estojo.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "6",
    title: "Caderno Universitário",
    productPrice: "7.99",
    productImg: require("../../assets/products/caderno.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "7",
    title: "Calculadora Científica",
    productPrice: "15.99",
    productImg: require("../../assets/products/calculadora.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "8",
    title: "Agenda Escolar",
    productPrice: "8.00",
    productImg: require("../../assets/products/agenda.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "9",
    title: "Tesoura Escolar",
    productPrice: "3.50",
    productImg: require("../../assets/products/tesoura.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "10",
    title: "Uniforme Escolar - Blusa de Frio",
    productPrice: "30.00",
    productImg: require("../../assets/products/frio.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "11",
    title: "Régua",
    productPrice: "2.50",
    productImg: require("../../assets/products/regua.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "12",
    title: "Lancheira Escolar",
    productPrice: "12.99",
    productImg: require("../../assets/products/lancheira.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "13",
    title: "Borracha",
    productPrice: "1.00",
    productImg: require("../../assets/products/borracha.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "14",
    title: "Corretivo",
    productPrice: "18.00",
    productImg: require("../../assets/products/corretivo.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "15",
    title: "Canetas Esferográficas - Pacote com 10",
    productPrice: "5.50",
    productImg: require("../../assets/products/caneta.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "16",
    title: "Lapis de Escrita",
    productPrice: "4.00",
    productImg: require("../../assets/products/lapis.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "17",
    title: "Lapiseira",
    productPrice: "1.50",
    productImg: require("../../assets/products/lapiseira.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "18",
    title: "Compasso",
    productPrice: "3.00",
    productImg: require("../../assets/products/compasso.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "19",
    title: "Garrafa de Água",
    productPrice: "4.50",
    productImg: require("../../assets/products/garrafa.png"),
    description: "Descrição do produto aqui.",
  },
  {
    id: "20",
    title: "Cola p/ Papel",
    productPrice: "10.00",
    productImg: require("../../assets/products/cola.png"),
    description: "Descrição do produto aqui.",
  }
];

export default products;